version: automatic_{branch}_build_{build}
image: Visual Studio 2017

branches:
  only:
  - master

skip_tags: true
configuration:
  - Release
  - Debug

environment:
  auth_token:
    secure: lwpoWmqAvm162iIBUx2QKEMGjqbXUEhC3Eq90igXe/nagZvlPFdofQS3d8HP+Zx4
  PRE_RELEASE: PRE_RELEASE
build:
  project: MUSHclient_2017.sln
  parallel: true
  verbosity: normal

artifacts:
- path: WinRel\MUSHclient.exe
  name: MUSHclient_Release
  type: File
- path: WinDebug\MUSHclient.exe
  name: MUSHclient_Debug
  type: File
- path: WinDebug\MUSHclient.pdb
  name: MUSHclient_Debug_PDB
  type: File

before_deploy:
- ps: >
    $path = if ($env:CONFIGURATION -eq "Release") { "WinRel\MUSHclient.exe" } else { "WinDebug\MUSHclient.exe" }
    & "C:\Program Files (x86)\Windows Kits\8.1\bin\x64\mt.exe" -manifest MUSHclient.exe.manifest -updateresource:$path`;#1
- git config --global credential.helper store
- ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:auth_token):x-oauth-basic@github.com`n"
- git tag -f latest_commit HEAD
- git push -f origin latest_commit

deploy:
- provider: GitHub
  tag: latest_commit_debug
  auth_token:
    secure: lwpoWmqAvm162iIBUx2QKEMGjqbXUEhC3Eq90igXe/nagZvlPFdofQS3d8HP+Zx4
  artifact: MUSHclient_Debug,MUSHclient_Debug_PDB
  prerelease: true
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: false
    configuration: Debug
- provider: GitHub
  tag: latest_commit
  auth_token:
    secure: lwpoWmqAvm162iIBUx2QKEMGjqbXUEhC3Eq90igXe/nagZvlPFdofQS3d8HP+Zx4
  artifact: MUSHclient_Release
  prerelease: true
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: false
    configuration: Release
